#!/usr/bin/env php
<?php

foreach (array( __DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('PERFORMER_VAGRANT_COMPOSER_INSTALL', $file);
        break;
    }
}

unset($file);

if (!defined('PERFORMER_VAGRANT_COMPOSER_INSTALL')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
    die(1);
}

require PERFORMER_VAGRANT_COMPOSER_INSTALL;

use Performer\VagrantBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;

if (file_exists($a = __DIR__ . '/../../../app/AppKernel.php')) {
    require_once $a;

    $input = new ArgvInput();
    $env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');
    $debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';

    $kernel = new AppKernel($env, $debug);
    $application = new Application($kernel);
    $application->run($input);
}